name: Update Project Tree

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual execution only

jobs:
  update-project-tree:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python for generating project tree
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Generate project tree in Markdown format
      - name: Generate project tree
        run: |
          mkdir -p artifacts
          python scripts/generate_tree.py
          mv data/project_tree.md artifacts/project_tree.md

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
        

      # Convert Markdown to HTML
      - name: Convert Markdown to HTML
        run: |
          pandoc -f markdown -t html artifacts/project_tree.md -o artifacts/project_tree.html

      - name: Debug generated files
        run: |
          echo "Checking artifacts directory..."
          ls -R artifacts || echo "Artifacts directory not found!"
          cat artifacts/project_tree.md || echo "Markdown file not found!"
          cat artifacts/project_tree.html || echo "HTML file not found!"

      - name: check directories before upload
        run:
          ls -R

      # Upload HTML content to Confluence
      - name: Upload project tree to Confluence
        env:
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
        run: |
          # Define variables
          SPACE_KEY="C2BFM" # Cambia esto por el nuevo Space Key
          PAGE_ID="22184038"     # Cambia esto por el nuevo Page ID
          SITE_URL="https://fjgonzalez25691.atlassian.net/wiki" # Cambia esto por tu nuevo site
          USER_EMAIL="fjgonzalez25691@gmail.com" # Ajusta si el email ha cambiado
          FILE_PATH="artifacts/project_tree.html"

      - name: Debug before Upload
        run: |
          echo "SPACE_KEY: $SPACE_KEY"
          echo "PAGE_ID: $PAGE_ID"
          echo "SITE_URL: $SITE_URL"
          echo "USER_EMAIL: $USER_EMAIL"
          echo "CONFLUENCE_API_TOKEN: $(echo -n $CONFLUENCE_API_TOKEN | wc -c) characters"
          echo "Checking HTML content in FILE_PATH:"
          cat $FILE_PATH || echo "HTML file not found!"

      # Upload HTML content to Confluence
      - name: Upload project tree to Confluence
        run:
          # Read HTML content
          CONTENT=$(cat $FILE_PATH)

      - name: Upload project tree to Confluence
        run: |
          curl -X PUT \
            -H "Authorization: Basic $(echo -n $USER_EMAIL:$CONFLUENCE_API_TOKEN | base64)" \
            -H "Content-Type: application/json" \
            -d "{\"version\":{\"number\":2},\"title\":\"Project Tree\",\"type\":\"page\",\"body\":{\"storage\":{\"value\":\"$CONTENT\",\"representation\":\"storage\"}}}" \
            --http1.1 \
            --data @payload.json \
            "$SITE_URL/rest/api/content/$PAGE_ID" \
            -o artifacts/curl_response.txt -v || echo "Error during curl execution"