name: Generate Project Tree

on:
  push:
    branches:
      - dev

jobs:
  generate-tree:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pyyaml

      - name: Generate Tree Files (JSON and YAML)
        run: python scripts/generate_tree.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: project-tree
          path: data/project_tree.*
