name: Update Project Tree

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual execution only

jobs:
  update-project-tree:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python for generating project tree
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Generate project tree in Markdown format
      - name: Generate project tree
        run: |
          mkdir -p artifacts
          python scripts/generate_tree.py
          mv data/project_tree.md artifacts/project_tree.md

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
        

      # Convert Markdown to HTML
      - name: Convert Markdown to HTML
        run: |
          pandoc -f markdown -t html artifacts/project_tree.md -o artifacts/project_tree.html

      # Upload HTML content to Confluence
      - name: Upload project tree to Confluence
        env:
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
        run: |
          # Define variables
          SPACE_KEY="C2BFM" # Cambia esto por el nuevo Space Key
          PAGE_ID="22184038"     # Cambia esto por el nuevo Page ID
          SITE_URL="https://fjgonzalez25691.atlassian.net/wiki" # Cambia esto por tu nuevo site
          USER_EMAIL="fjgonzalez25691@gmail.com" # Ajusta si el email ha cambiado
          FILE_PATH="artifacts/project_tree.html"

          # Read HTML content
          CONTENT=$(cat $FILE_PATH)

          # Upload to Confluence using API
          curl -X PUT \
            -H "Authorization: Basic $(echo -n $USER_EMAIL:$CONFLUENCE_API_TOKEN | base64)" \
            -H "Content-Type: application/json" \
            -d "{\"version\":{\"number\":2},\"title\":\"Project Tree\",\"type\":\"page\",\"body\":{\"storage\":{\"value\":\"$CONTENT\",\"representation\":\"storage\"}}}" \
            "$SITE_URL/rest/api/content/$PAGE_ID"
